name: 有效性检测

on:
  schedule:
    - cron: '0 */12 * * *' # 这里更改自动运行的时间，每12小时运行一次
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Upgrade pip and install dependencies
        run: |
          pip install --upgrade pip
          pip install selenium requests futures eventlet opencv-python Beautifulsoup4 translate termcolor func_timeout replace input opencc pypinyin pytz tqdm

      - name: Run iptv
        run: python ${{ github.workspace }}/IPTV/V4检测优选.py

      #- name: Run iptv
        #run: python ${{ github.workspace }}/IPTV/分类去重.py

      # 提交和推送的步骤，不再检查文件是否发生变化
      - name: Commit and push changes
        run: |
          git config --local user.email "actions@126.com"
          git config --local user.name "GitHub Action"
          git add .
          # 即使没有文件改变，也会提交一个空的提交
          git commit --allow-empty -m "Scheduled workflow run"
          git pull --rebase
          git push -f
